name: Auto Update Dependencies

on:
  schedule:
    - cron: "0 0 */3 * *"   # every 3 days
  push:
    branches:
      - Automation_script
  workflow_dispatch:        

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyyaml requests

      - name: Run update agent
        run: |
          python3 Agent/check_updates.py
          python3 Agent/run_update.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add requirements.lock logs/ || true
          git commit -m "Automated dependency update" || echo "No changes to commit"
          git push
